[package]
name = "tcp-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lineagedb-tcp-server"
path = "src/main.rs"

[dependencies]
database = { path = "../../database" }
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
